name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - run: corepack prepare pnpm@9.12.0 --activate
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm -C packages/dnsweeper run build
      - run: pnpm -C packages/dnsweeper run test
      - run: pnpm -C packages/dnsweeper run lint
      - run: pnpm -C packages/dnsweeper run test -- --coverage
      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: packages/dnsweeper/.tmp/coverage
